server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    mvc:
      static-path-pattern: /**
      hiddenmethod:
        filter:
          enabled: true

    web:
      resources:
        static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/

    thymeleaf:
          cach: false
          mode: LEGACYHTML5
          prefix: classpath:/templates/
          suffix: .html
          content-type: text/html
          cache: false
          encoding: utf-8

mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml